name: Run SiEPIC-Tool Layout tests 

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - master


jobs:
  test_layouts:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

        # can also specify python version if needed
      - name: setup python
        uses: actions/setup-python@v4

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install klayout numpy scipy pytest pytest-cov SiEPIC

      - name: Test with pytest
        run: pytest --cov=klayout/siepic_ebeam_pdk   --cov-report=xml
  
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true

